services:
  octopus:
    image: ghcr.io/loserrc/octopus:v0.1.1
    ports:
       - '8080:8080'
    volumes:      
       - '/path/to/data:/app/data'
    container_name: octopus
    restart: unless-stopped
